# Generated by Django 5.0 on 2023-12-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_images_taag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TAag',
            new_name='Tag',
        ),
    ]
