# Generated by Django 5.0 on 2023-12-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='message',
            field=models.TextField(default='example'),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='name',
            field=models.CharField(default='name2', max_length=200),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='subject',
            field=models.CharField(default='example', max_length=200),
        ),
    ]
