# Generated by Django 5.0 on 2023-12-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_contact_us_email_contact_us_message_contact_us_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
