# Generated by Django 5.0 on 2023-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_alter_filter_price_price_alter_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('GAP Certified', 'GAP Certified'), ('No', 'No')], max_length=100),
        ),
    ]
